### ISSUE TITLE
Source list only shows TV and HDMI

### ISSUE THREAD

**Issue by AngelAsenov** [ollo69/ha-samsungtv-smart#370]
**Describe the bug**
Source list only shows TV and HDMI

**Expected behavior**
Source list was previously correctly showing "Playstation 5" and "Vivacom"

**Environment details:**
 - Environment (HASSIO, Raspbian, etc):
 - Home Assistant version installed:  15.1
 - Component version installed: 0.13.5
 - Last know working version: 0.13.5 ?
 - TV model: UE65DU8072UXXH

**Output of HA logs**

Not sure where to retrieve those. In the config/home-assistant.log there is nothing relevant. 

**Additional context**

- Currently I don't have a configured Source list
- Currently I have 4 Apps configured in the Application list ( thus 4 additional entries in the Source dropdown )
- All of the sources work

The issue that I have is that before, instead of "TV" and "HDMI" I had the actual sources names on the TV coming from SmartThings which are "Playstation 5" and "Viivacom" ( a TV Box from a provider ). 

Suddenly this is no longer the case without me changing anything and this breaks some of my automations. Note: I am able to switch the sources without any issues from SmartThings and also from HA but why does it suddenly show "TV" and "HDMI" ?

I tried to debug or find out additional information about this wherever I could but I cannot find anything. Could someone please advise what could be the issue and/or suggest from where I should extract logs for additional information ?

Best Regards,
Angel Asenov

**Comment by AngelAsenov** [comment]
Maybe worth mentioning as well is that sending a command such as "ST_HDMI1" no longer works as well

**Comment by djs42012** [comment]
Just ran into the same. Reconfiguring from scratch using a new PAT resolved it. Not ideal but it got me back up and running. It broke after about 24 hours for me the first time.

**Comment by TBrozovich** [comment]
Hello, I am having the same issue. What is the solution to get all of my HDMI sources to show?

**Comment by KlausHans** [comment]
Got the same issue. I switched to this integration because with the official one in HA it is the same problem. I thought this one would solve this.
> Reconfiguring from scratch using a new PAT resolved it

What do you mean with that? Reconfiguring from scratch = Factory reset of the TV? What is a new PAT?

**Comment by Merril-r** [comment]
I am having the same issue. Is there a place you can manually add the apps?

**Comment by pjrish** [comment]
I was also having this issue with the source list until I re-sync'd the TV and the SmartThings app.  Now sources are appearing and working correctly again.

**Comment by AngelAsenov** [comment]
> I was also having this issue with the source list until I re-sync'd the TV and the SmartThings app. Now sources are appearing and working correctly again.

Hi mate, thank you for the update. What do you mean by resynced them ? Just delete and add again ?

I already tried everything from the TV, from SmartThings and from HA.

I think I tried to re-add one of the TVs to SmartThings as well but this didn't even fix the issue at all ( while re-adding in HA in this integration fixes it for 24h )

**Comment by pjrish** [comment]
> Hi mate, thank you for the update. What do you mean by resynced them ? Just delete and add again ?

I didn't delete anything.  I went into the SmartThings app and realized the TV was showing "unavailable" and would not respond to commands.  I opened the device and clicked the 3 dots, then selected "Update Data."  I also opened the "Sources" menu in the SmartThings App.

On the TV, I went into the SmartThings App, just to make sure it was communicating properly - no idea if this had an impact or not.

Anyways, after doing both of those, Home Assistant now sees the inputs and automatically re-labels them to the friendly names that I had previously defined in the "Source List" settings on the App as shown below:
'''
HDMI 3: ST_HDMI3
Game: ST_HDMI2
TIVO: ST_HDMI1
'''

**Comment by AngelAsenov** [comment]
issues persists for me, tried again after re-adding everything, everywhere. Once 24h have passed, it stops seeing it, even though the API key for SmartThings still works ( tried it manually ).

**Comment by ollo69** [comment]
Closing this, resolved with last release.

**Comment by KlausHans** [comment]
Does not work for me with the update (i am not using Smartthings). I still get only TV and HDMI, even after readding the tv via this integration.

**Comment by ollo69** [comment]
> Does not work for me with the update (i am not using Smartthings). I still get only TV and HDMI, even after readding the tv via this integration.

If you don't use SmartThings it is normal that integration only report TV and HDMI. This is one of the additional features provided by SmartThings functionality.

**Comment by KlausHans** [comment]
Thanks for the info. Is this limited by the tv api or is the feature missing in this integration?

**Comment by ollo69** [comment]
Limited TV api

**Comment by KlausHans** [comment]
Thanks!
